export const INGREDIENT_ADD = 'INGREDIENT_ADD';
export const INGREDIENT_DELETE = 'INGREDIENT_DELETE';
export const INGREDIENTS_SET = 'INGREDIENTS_SET';
export const INGREDIENTS_FETCH_FAILED = 'INGREDIENTS_FETCH_FAILED';

export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';